
services:
  db:
    image: postgis/postgis:16-master
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .

    volumes:
      - .:/code
      - ./temp/:/tmp/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ".env"

# sudo docker-compose up --build
#(Made some changes in this file to best fit the Django REST Api, was previously set for FastAPI)